import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

class SummaryPdfService {
  Future<File> saveSummaryPdf({
    required String title,
    required String summary,
  }) async {
    final directory = await _resolveDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final safeTitle = _sanitizeFileName(title);
    final filename = '${safeTitle}_summary_$timestamp.pdf';
    final outputFile = File(p.join(directory.path, filename));

    final bytes = _buildPdfBytes(
      title: title.trim().isEmpty ? 'Study Summary' : title.trim(),
      summary: summary,
    );

    await outputFile.writeAsBytes(bytes, flush: true);
    return outputFile;
  }

  Future<Directory> _resolveDirectory() async {
    try {
      final downloads = await getDownloadsDirectory();
      if (downloads != null) {
        if (!await downloads.exists()) {
          await downloads.create(recursive: true);
        }
        return downloads;
      }
    } catch (e) {
      // Downloads directory unavailable on this platform, falling back to app documents
      // Consider logging: debugPrint('Downloads directory unavailable: $e');
    }

    final appDocs = await getApplicationDocumentsDirectory();
    final exportsDir = Directory(p.join(appDocs.path, 'exports'));
    if (!await exportsDir.exists()) {
      await exportsDir.create(recursive: true);
    }
    return exportsDir;
  }

  String _sanitizeFileName(String raw) {
    final compact = raw.trim().replaceAll(RegExp(r'\s+'), '_');
    final sanitized = compact.replaceAll(RegExp(r'[^a-zA-Z0-9_\-]'), '');
    if (sanitized.isEmpty) return 'studyspace';
    return sanitized.length > 40 ? sanitized.substring(0, 40) : sanitized;
  }

  Uint8List _buildPdfBytes({
    required String title,
    required String summary,
  }) {
    final lines = _buildWrappedLines(title: title, summary: summary);
    const int maxLinesPerPage = 44;

    final pages = <List<String>>[];
    for (var i = 0; i < lines.length; i += maxLinesPerPage) {
      final end = min(i + maxLinesPerPage, lines.length);
      pages.add(lines.sublist(i, end));
    }
    if (pages.isEmpty) {
      pages.add(const ['No summary content']);
    }

    final objectMap = <int, String>{};
    final pageObjectIds = <int>[];
    final contentObjectIds = <int>[];

    var nextObjectId = 3; // 1: catalog, 2: pages
    for (var i = 0; i < pages.length; i++) {
      final pageId = nextObjectId++;
      final contentId = nextObjectId++;
      pageObjectIds.add(pageId);
      contentObjectIds.add(contentId);
    }
    final fontId = nextObjectId++;

    objectMap[fontId] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';

    for (var i = 0; i < pages.length; i++) {
      final pageId = pageObjectIds[i];
      final contentId = contentObjectIds[i];
      final stream = _buildPageStream(pages[i]);

      objectMap[contentId] = '<< /Length ${utf8.encode(stream).length} >>\n'
          'stream\n'
          '$stream\n'
          'endstream';

      objectMap[pageId] = '<< /Type /Page /Parent 2 0 R '
          '/MediaBox [0 0 595 842] '
          '/Resources << /Font << /F1 $fontId 0 R >> >> '
          '/Contents $contentId 0 R >>';
    }

    objectMap[1] = '<< /Type /Catalog /Pages 2 0 R >>';
    objectMap[2] = '<< /Type /Pages /Kids [${pageObjectIds.map((id) => '$id 0 R').join(' ')}] /Count ${pageObjectIds.length} >>';

    final totalObjects = nextObjectId - 1;
    final offsets = List<int>.filled(totalObjects + 1, 0);

    final buffer = StringBuffer();
    buffer.write('%PDF-1.4\n');
    var currentOffset = utf8.encode('%PDF-1.4\n').length;

    for (var id = 1; id <= totalObjects; id++) {
      offsets[id] = currentOffset;
      final objectBody = objectMap[id] ?? '';
      final objectBlock = '$id 0 obj\n$objectBody\nendobj\n';
      buffer.write(objectBlock);
      currentOffset += utf8.encode(objectBlock).length;
    }

    final xrefOffset = currentOffset;
    buffer.write('xref\n');
    buffer.write('0 ${totalObjects + 1}\n');
    buffer.write('0000000000 65535 f \n');

    for (var id = 1; id <= totalObjects; id++) {
      final entry = '${offsets[id].toString().padLeft(10, '0')} 00000 n \n';
      buffer.write(entry);
    }

    buffer.write('trailer\n');
    buffer.write('<< /Size ${totalObjects + 1} /Root 1 0 R >>\n');
    buffer.write('startxref\n');
    buffer.write('$xrefOffset\n');
    buffer.write('%%EOF');

    return Uint8List.fromList(utf8.encode(buffer.toString()));
  }

  List<String> _buildWrappedLines({
    required String title,
    required String summary,
  }) {
    final output = <String>[
      title,
      '',
      'Generated by MyStudySpace AI',
      '',
    ];

    final rawLines = summary
        .replaceAll('\r', '\n')
        .split('\n')
        .map((line) => line.trim())
        .where((line) => line.isNotEmpty)
        .toList();

    for (var raw in rawLines) {
      final cleaned = raw
          .replaceFirst(RegExp(r'^[-*]+\s*'), '')
          .replaceAll(RegExp(r'\s+'), ' ')
          .trim();
      if (cleaned.isEmpty) continue;

      output.addAll(_wrapLine(cleaned, 88));
    }

    return output.map(_toPdfSafeText).toList();
  }

  List<String> _wrapLine(String line, int maxChars) {
    if (line.length <= maxChars) return [line];

    final words = line.split(RegExp(r'\s+'));
    final wrapped = <String>[];
    final current = StringBuffer();

    for (final word in words) {
      if (word.isEmpty) continue;
      if (current.isEmpty) {
        current.write(word);
        continue;
      }

      final projected = '${current.toString()} $word';
      if (projected.length <= maxChars) {
        current.write(' $word');
      } else {
        wrapped.add(current.toString());
        current
          ..clear()
          ..write(word);
      }
    }

    if (current.isNotEmpty) {
      wrapped.add(current.toString());
    }
    return wrapped;
  }

  String _buildPageStream(List<String> lines) {
    final stream = StringBuffer();
    stream.writeln('BT');
    stream.writeln('/F1 12 Tf');
    stream.writeln('1 0 0 1 48 802 Tm');

    for (var i = 0; i < lines.length; i++) {
      final escaped = _escapePdfText(lines[i]);
      stream.writeln('($escaped) Tj');
      if (i != lines.length - 1) {
        stream.writeln('0 -16 Td');
      }
    }

    stream.writeln('ET');
    return stream.toString();
  }

  String _toPdfSafeText(String text) {
    final buffer = StringBuffer();
    for (final code in text.runes) {
      if (code >= 32 && code <= 126) {
        buffer.writeCharCode(code);
      } else {
        buffer.write('?');
      }
    }
    return buffer.toString();
  }

  String _escapePdfText(String text) {
    return text
        .replaceAll(r'\', r'\\')
        .replaceAll('(', r'\(')
        .replaceAll(')', r'\)');
  }
}
